# https://taskfile.dev

version: '3'

vars:
  GREETING: Welcome to the learn-go-cobra-cli!

tasks:
  default:
    desc: Welcome message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:go:
    desc: Setup pre-requisites
    cmds: 
      - go install github.com/spf13/cobra-cli@latest
      - go install github.com/goreleaser/goreleaser/v2@latest
    silent: true

  setup:
    desc: Setup pre-requisites
    deps:
      - setup:go 
    silent: true

  test:
    desc: Test learn go cobra cli
    dir: datacli
    cmds:
      - go test ./...
    silent: true

  versions:
    desc: Versions of installations
    cmds:
      - goreleaser --version

  build:
    desc: Perform a build
    cmds:
      - goreleaser build --snapshot --clean

  release:dry:
    desc: Run a dry run release
    cmds:
      - goreleaser release --snapshot --clean

  # release:
  #   desc: Tag and release
  #   cmds:
  #     - git tag v0.1.0
  #     - git push origin v0.1.0

  install:system:
    desc: Install the CLI system wide
    cmds:
      - sudo cp ./dist/datagriff_linux_amd64_v1/datagriff-datacli /usr/local/bin/