# https://taskfile.dev

version: '3'

vars:
  GREETING: Welcome to the learn-go-cobra-cli!

tasks:
  default:
    desc: Welcome message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:go:
    desc: Setup pre-requisites
    cmds: 
      - go install github.com/spf13/cobra-cli@latest
      - go install github.com/goreleaser/goreleaser/v2@latest
    silent: true

  setup:
    desc: Setup pre-requisites
    deps:
      - setup:go 
    silent: true

  test:
    desc: Test learn go cobra cli
    dir: datacli
    cmds:
      - go test ./...
    silent: true